Kubernetes security
otus-kuber-2020-11/ValeriyTyutyunnik_platform pull request #4
Opened 2021-01-02 23:35 UTC by ValeriyTyutyunnik

# Выполнено ДЗ №

 - [x] Основное ДЗ

## В процессе сделано:
- Создание и выдача ролей:
- Выдача роли admin в рамках кластера сервис-аккаунту bob
- Сервис аккаунт dave без доступа к кластеру
- Создан namespace prometheus, и сервис аккаунт carol в ns prometheus
- Всем service account в ns prometheus выданы права на get/list/watch в отношении Pods кластера
Создан namespace dev, в рамках которого:
- Создан Service account jane c ролью admin в рамках dev
- Создан Service account ken с ролью view в рамках dev

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist:
 - [ ] Выставлен label с темой домашнего задания

2021-01-03 14:00 UTC, Jasstkn requested changes

2021-01-03 14:00 UTC, Jasstkn commented on kubernetes-security/task-03/03-jane-admin-role.yaml
> +---
Во время прогона тестов всплыла ошибка:
> + kubectl auth can-i create deployments --as system:serviceaccount:dev:jane -n dev
no - RBAC: role.rbac.authorization.k8s.io "admin" not found
+ exit 3

скорее всего, вам необходимо изменить kind на ClusterRole, попробуйте применить манифесты и выполнить команду из ошибки - она должна завершиться успешно.

2021-01-03 14:01 UTC, Jasstkn commented on kubernetes-security/task-03/03-jane-admin-role.yaml
> +---
Также, если вам не затруднит, переименуйте пожалуйста папки из task-0X в task0X - на из названия ориентированы автотесты

2021-01-03 14:21 UTC, ValeriyTyutyunnik commented on kubernetes-security/task-03/03-jane-admin-role.yaml
> +---
Да, там явно ClusterRole.

Автопроверки скоро вернутся?

2021-01-08 17:42 UTC, Jasstkn commented on kubernetes-security/task-03/03-jane-admin-role.yaml
> +---
Вернутся - работаем над этим)

2021-01-08 17:54 UTC, Jasstkn approved these changes
Теперь все верно 👍

2021-01-08 17:54 UTC, merged